/home/wangchengxuan/pulp-master/./rtl/tb/riscv_pkg.sv
/home/wangchengxuan/pulp-master/./rtl/tb/jtag_pkg.sv
/home/wangchengxuan/pulp-master/./rtl/tb/pulp_tap_pkg.sv
/home/wangchengxuan/pulp-master/./rtl/tb/tb_clk_gen.sv
/home/wangchengxuan/pulp-master/./rtl/tb/tb_fs_handler.sv
/home/wangchengxuan/pulp-master/./rtl/tb/dpi_models/dpi_models.sv
/home/wangchengxuan/pulp-master/./rtl/tb/tb_driver/tb_driver.sv
/home/wangchengxuan/pulp-master/./rtl/tb/tb_pulp.sv
/home/wangchengxuan/pulp-master/./rtl/tb/SimJTAG.sv
/home/wangchengxuan/pulp-master/./rtl/tb/SimDTM.sv
/home/wangchengxuan/pulp-master/./rtl/vip/spi_flash/S25fs256s/model/s25fs256s.v
/home/wangchengxuan/pulp-master/./rtl/vip/i2c_eeprom/24FC1025.v
/home/wangchengxuan/pulp-master/./rtl/vip/hyperflash_model/s26ks512s.v
/home/wangchengxuan/pulp-master/./rtl/vip/hyperram_model/s27ks0641.v
/home/wangchengxuan/pulp-master/./rtl/vip/psram_model/*.vp_modelsim
/home/wangchengxuan/pulp-master/./rtl/vip/i2s/i2c_if.v
/home/wangchengxuan/pulp-master/./rtl/vip/i2s/i2s_vip_channel.sv
/home/wangchengxuan/pulp-master/./rtl/vip/i2s/i2s_vip.sv
/home/wangchengxuan/pulp-master/./rtl/vip/spi_master_padframe.sv
/home/wangchengxuan/pulp-master/./rtl/vip/uart_tb_rx.sv
/home/wangchengxuan/pulp-master/./rtl/vip/camera/cam_vip.sv
-incdir /home/wangchengxuan/pulp-master/./rtl/pulp/../includes
/home/wangchengxuan/pulp-master/./rtl/pulp/../../ips/pulp_soc/rtl/pulp_soc/pkg_soc_interconnect.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/../../ips/axi/axi/src/axi_pkg.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/jtag_tap_top.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/pad_control.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/pad_frame.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/cluster_domain.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/safe_domain.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/soc_domain.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/rtc_date.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/rtc_clock.sv
/home/wangchengxuan/pulp-master/./rtl/pulp/pulp.sv
